name: AVIS_NETWORK_DISPATCH
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  signal_others:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target_repo: ['NEXUS', 'Sentinel', 'Cyborg',  'AVIS']
    steps:
      - name: AVIS_SECRET_GATE
        run: |
          if [ -z "${{ secrets.MERC_G_PAT }}" ]; then
            echo "::error::[GATE_FAILURE] MERC_G_PAT is empty. The robot has no keys."
            exit 1
          fi

      - name: Emit Verified Signal
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.MERC_G_PAT }}
          repository: ${{ github.repository_owner }}/${{ matrix.target_repo }}
          event-type: nexus_update_signal
          client-payload: '{"status": "compiled", "fvs_vector": "0xF"}'
